services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./customer/schema.sql:/docker-entrypoint-initdb.d/1-customer-schema.sql
      - ./customer/seed.sql:/docker-entrypoint-initdb.d/2-customer-seed.sql
      - ./ticket/schema.sql:/docker-entrypoint-initdb.d/3-ticket-schema.sql

volumes:
  pgdata:
